name: Nighty Build

on:
  push:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build CA in ${{ matrix.branch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, dev]

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4

      - name: Install CA Build Tools
        run: sudo npm install -g cabuildtools

      - name: Checkout CA
        env:
          branch: ${{ matrix.branch }}
        run: |
          mkdir ca
          git clone -v --branch $branch --depth 1 "https://gitee.com/projectxero/ca.git" "ca"

      - name: Configure publish
        run: |
          cd ca
          echo @method local > ./config/publish.txt
          echo @destPath pub >> ./config/publish.txt

      - name: Prepare publish
        run: |
          cd ca
          cabuild preparePublish

      - name: Build and Publish
        run: |
          cd ca
          cabuild buildSnapshot
          cabuild publishSnapshot
          cabuild buildRelease
          cabuild publishRelease
          cabuild publishHotfix

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.branch }} distrobutions
          path: ca/build/dist

      - name: Upload Outputs as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.branch }} outputs
          path: ca/build/outputs

      - name: Upload to Git#checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.PUSH_REPO }}
          token: ${{ secrets.PUSH_TOKEN }}
          path: gitpub

      - name: Upload to Git#checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.PUSH_REPO }}
          token: ${{ secrets.PUSH_TOKEN }}
          path: gitpub
          fetch-depth: 0
          persist-credentials: false

      - name: Upload to Git#copy
        run: |
          cp -f -a ca/build gitpub

      - name: Upload to Git#commit
        env:
          email: ${{ secrets.PUSH_EMAIL }}
        run: |
          cd gitpub
          git config --local user.email $email
          git config --local user.name "CArrotProject[BOT]"
          date %Y%m%d > ../message.txt
          git commit -F ../message.txt -a

      - name: Upload to Git#push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: gitpub
          repository: ${{ secrets.PUSH_REPO }}
          branch: main
          github_token: ${{ secrets.PUSH_TOKEN }}

      - name: Package Workspace
        run: zip -r -S -9 -v workspace.zip .

      - name: Upload Workspace as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.branch }} workspace
          path: workspace.zip
