name: Nighty Build

on:
  push:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build CA in ${{ matrix.branch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, dev]

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4

      - name: Install CA Build Tools
        run: sudo npm install -g cabuildtools

      - name: Checkout CA
        env:
          branch: ${{ matrix.branch }}
        run: |
          mkdir ca
          sudo git clone -v --branch $branch --depth 1 "https://gitee.com/projectxero/ca.git" "ca"
          cd ca

      - name: Configure publish
        run: |
          mkdir pub
          ls -R
          echo @method local > config/publish.txt
          echo @destPath pub >> config/publish.txt

      - name: Prepare publish
        run: |
          cabuild preparePublish

      - name: Build as snapshot
        run: |
          cabuild buildSnapshot
          cabuild publishSnapshot

      - name: Build as release
        run: |
          cabuild buildRelease
          cabuild publishRelease
          ls -R
